# Generated by Django 3.1.1 on 2025-09-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='conversion_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
