# Generated by Django 3.1.1 on 2025-09-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_lead_conversion_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='enriched_job_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='enrichment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='routed_to',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='routing_reason',
            field=models.TextField(blank=True),
        ),
    ]
