# Generated by Django 3.1.1 on 2025-05-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_assignment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstaff',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
