# Generated by Django 3.1.1 on 2025-05-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20250513_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(default='Default Session', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
