# Generated by Django 3.1.1 on 2025-05-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20250514_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='course',
        ),
        migrations.AddField(
            model_name='staff',
            name='courses',
            field=models.ManyToManyField(to='main_app.Course'),
        ),
    ]
