# Generated by Django 3.1.1 on 2025-05-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20250519_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='exam',
            new_name='max_score',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='exam_title',
            field=models.CharField(default='Final Exam', max_length=100),
        ),
    ]
