# Generated by Django 3.1.1 on 2025-05-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20250519_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='payment_period',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half Yearly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20),
        ),
    ]
